SELECT 
            p.ORG_ID,m.MERCHANT_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_TIME
        FROM TRA_REFUND_ORG_POLICY p
        INNER JOIN CMS_MERCHANT m
        ON p.ORG_ID = m.MERCHANT_ID
        WHERE p.ORG_ID = CIB_622295
        ORDER BY p.CREATE_TIME DESC
;-- -. . -..- - / . -. - .-. -.--
SELECT 
            p.ORG_ID,m.MERCHANT_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_TIME
        FROM TRA_REFUND_ORG_POLICY p
        INNER JOIN CMS_MERCHANT m
        ON p.ORG_ID = m.MERCHANT_ID
        WHERE p.ORG_ID = 'CIB_622295'
        ORDER BY p.CREATE_TIME DESC
;-- -. . -..- - / . -. - .-. -.--
SELECT 
            p.ORG_ID,m.MERCHANT_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_TIME
        FROM TRA_REFUND_ORG_POLICY p
        INNER JOIN CMS_MERCHANT m
        ON p.ORG_ID = m.MERCHANT_ID
        WHERE p.ORG_ID = 101590000276
        ORDER BY p.CREATE_TIME DESC
;-- -. . -..- - / . -. - .-. -.--
SELECT 
            p.ORG_ID,m.MERCHANT_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_TIME
        FROM TRA_REFUND_ORG_POLICY p
        INNER JOIN CMS_MERCHANT m
        ON p.ORG_ID = m.MERCHANT_ID
        WHERE p.ORG_ID = '101590000276'
        ORDER BY p.CREATE_TIME DESC
;-- -. . -..- - / . -. - .-. -.--
SELECT
            p.ORG_ID,c.CHANNEL_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_TIME
        FROM TRA_REFUND_ORG_POLICY p
        INNER JOIN CMS_CHANNEL c
        ON p.ORG_ID = c.CHANNEL_ID
        WHERE c.CHANNEL_ID = '101590000276' OR c.PARENT_CHANNEL = '101590000276'
        ORDER BY p.CREATE_TIME DESC
;-- -. . -..- - / . -. - .-. -.--
SELECT
            c.CHANNEL_ID,c.CHANNEL_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_EMP,p.CREATE_TIME
        FROM CMS_CHANNEL c
        LEFT JOIN TRA_REFUND_ORG_POLICY p
        ON c.CHANNEL_ID = p.ORG_ID
        WHERE c.PARENT_CHANNEL = CIB_379560
        ORDER BY p.CREATE_TIME DESC
;-- -. . -..- - / . -. - .-. -.--
SELECT
            c.CHANNEL_ID,c.CHANNEL_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_EMP,p.CREATE_TIME
        FROM CMS_CHANNEL c
        LEFT JOIN TRA_REFUND_ORG_POLICY p
        ON c.CHANNEL_ID = p.ORG_ID
        WHERE c.PARENT_CHANNEL = 'CIB_379560'
        ORDER BY p.CREATE_TIME DESC
;-- -. . -..- - / . -. - .-. -.--
SELECT
            p.ORG_POLICY_ID,c.CHANNEL_ID ORG_ID,c.CHANNEL_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_EMP,p.CREATE_TIME
        FROM TRA_REFUND_ORG_POLICY p
        INNER JOIN CMS_CHANNEL c
        ON p.ORG_ID = c.CHANNEL_ID
        WHERE c.PARENT_CHANNEL = 'CIB_379560'
        ORDER BY p.CREATE_TIME DESC
;-- -. . -..- - / . -. - .-. -.--
SELECT
            p.ORG_POLICY_ID,p.ORG_ID,m.MERCHANT_NAME ORG_NAME,p.ORG_TYPE,p.REFUND_COUNT_LIMIT,p.CREATE_EMP,p.CREATE_TIME
        FROM TRA_REFUND_ORG_POLICY p
        INNER JOIN CMS_MERCHANT m
        ON p.ORG_ID = m.MERCHANT_ID
        WHERE p.ORG_ID = '5792000001'
        ORDER BY p.CREATE_TIME DESC